name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main

jobs:

  kubernetes:
    concurrency: 2
    name: Kubernetes
    runs-on: actuated
    strategy:
      matrix:
#        k3s: [v1.17, v1.18, v1.19, v1.20, v1.21, v1.22, v1.23]
        k3s: [v1.19, v1.22, v1.23, v1.24]
    steps:
      - uses: actions/checkout@v1

      - name: Create Kubernetes ${{ matrix.k3s }} cluster
        run: |
          arkade get k3sup
          mkdir -p $HOME/.kube/
          $HOME/.arkade/bin/k3sup install --local --k3s-channel ${{ matrix.k3s }} --local-path $HOME/.kube/kubeconfig
          cat $HOME/.kube/kubeconfig

      - name: Test crds
        run: |
          export KUBECONFIG=$HOME/.kube/kubeconfig
          echo "waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes
          echo "Applying CRD"
          kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/master/artifacts/crds/inlets.inlets.dev_tunnels.yaml
