name: k3s-test-matrix


on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main
  workflow_dispatch:


jobs:
  kubernetes:
    name: k3s-test-${{ matrix.k3s }}
    runs-on: actuated

    strategy:
      matrix:
        k3s: [v1.19, v1.20, v1.21, v1.22, v1.23, v1.24, v1.25, v1.26]

    steps:
      - uses: actions/checkout@v1
      - name: Setup mirror
        uses: self-actuated/hub-mirror@master
      - uses: alexellis/setup-arkade@v2
      - uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          k3sup: latest

      - name: Create Kubernetes ${{ matrix.k3s }} cluster
        run: |
          mkdir -p $HOME/.kube/
          k3sup install \
            --local \
            --k3s-channel ${{ matrix.k3s }} \
            --local-path $HOME/.kube/config \
            --merge \
            --context default
          cat $HOME/.kube/config
          
          k3sup ready --context default
          kubectl config use-context default
          
          # Just an extra test on top.
          echo "Waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes -o wide
          
      - name: Test crds
        run: |
          echo "Applying CRD"
          kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/artifacts/crds/openfaas.com_functions.yaml
          
